name : Resuable-Workflow 

on :
  workflow_call :
    inputs :
      image :
        required : true
      userid :
        required : true
      tag :
        required : true
    secrets :
      DOCKER_USERNAME :
        required : true
      DOCKER_PASSWORD :
        required : true
        
jobs :

  Building-and-Pushing-DockerImage :
   
    runs-on : self-hosted
    
    steps :
    
      - name : Giving permission to our Repository
        uses: actions/checkout@v2

      - name: docker-upload
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
         image: ${{ inputs.userid }}/${{ inputs.image }}:${{ inputs.tag }}
         registry: docker.io
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
           
